### ISSUE TITLE
SequelizeDatabaseError

### ISSUE THREAD

**Issue by shivanandbhangari** [waiyaki/postgres-express-node-tutorial#1]
Nice tutorial sir, but i am getting Dequelize DatabaseError while trying to request  localhost:8000/api/todos in postman. The below is the output

{
    "name": "SequelizeDatabaseError",
    "parent": {
        "name": "error",
        "length": 115,
        "severity": "ERROR",
        "code": "42P01",
        "position": "13",
        "file": "src\\backend\\parser\\parse_relation.c",
        "line": "984",
        "routine": "parserOpenTable",
        "sql": "INSERT INTO \"Todos\" (\"id\",\"title\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'first-todo','2017-06-15 06:11:49.889 +00:00','2017-06-15 06:11:49.889 +00:00') RETURNING *;"
    },
    "original": {
        "name": "error",
        "length": 115,
        "severity": "ERROR",
        "code": "42P01",
        "position": "13",
        "file": "src\\backend\\parser\\parse_relation.c",
        "line": "984",
        "routine": "parserOpenTable",
        "sql": "INSERT INTO \"Todos\" (\"id\",\"title\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'first-todo','2017-06-15 06:11:49.889 +00:00','2017-06-15 06:11:49.889 +00:00') RETURNING *;"
    },
    "sql": "INSERT INTO \"Todos\" (\"id\",\"title\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'first-todo','2017-06-15 06:11:49.889 +00:00','2017-06-15 06:11:49.889 +00:00') RETURNING *;"
}

Can you please help me out to resolve this error. Thank you

**Comment by waiyaki** [comment]
Hey @shivanandbhangari.

After creating the db and writing the code for models and the migrations, make sure you run 
```
sequelize db:migrate
```
to actually create the necessary tables in the db.
Let me know if that fixes that issue.

**Comment by shivanandbhangari** [comment]
@waiyaki 
Yes it works thanks a lot Waiyaki. Super exapmle, learnt lot from this code. Thank you once again.

**Comment by waiyaki** [comment]
Great, thank you!

**Comment by jerrychong25** [comment]
> Hey @shivanandbhangari.
> 
> After creating the db and writing the code for models and the migrations, make sure you run
> 
> ```
> sequelize db:migrate
> ```
> 
> to actually create the necessary tables in the db.
> Let me know if that fixes that issue.

Thanks!
